version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: go-api
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/?authSource=admin

volumes:
  mongo-data:
